name = "Createpack"
author = "cosmodd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d87f04a97adb6fe341b71de176d898884ce680debfc5e38d35520dc7352fbeff"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
