name = "Createpack"
author = "cosmodd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c4277cd5cb870b54a8d3c0d466b5d04a4662edc3b7cf85d475788bc89d75ffa"

[versions]
forge = "47.2.21"
minecraft = "1.20.1"
